### ISSUE TITLE
朝ご飯の調達

### ISSUE THREAD

**Issue by Sntree2mi8** [jphacks/TK_1704#1]
朝ご飯を買ってくる

**Comment by Sntree2mi8** [comment]
白いたい焼き
バナナ
生チョコクレープ
かき揚げそば

**Comment by mr04vv** [comment]
サンドウィッチ
カレーパン
焼き鮭おにぎり

**Comment by shooontan** [comment]
* 日高昆布おにぎり
* 鶏照焼と2色そぼろ弁当(あたためるの忘れた)

**Comment by s-kamada** [comment]
【買ったもの】
大きなおにぎり(唐揚げマヨネーズ)
ミックスサンドイッチ

**Comment by nakarin0528** [comment]
- アメリカンドック
- 照り焼きチキン&明太ポテト
- 提供されたコーヒー
