### ISSUE TITLE
#名前決める

### ISSUE THREAD

**Issue by Sntree2mi8** [jphacks/TK_1704#5]
# どんどん挙げていこう！

**Comment by Sntree2mi8** [comment]
とりあえずlivetech?でいい感じ？

**Comment by s-kamada** [comment]
【コンセプト】
・アーティストとオーディエンスの一体感
・従来のライブはアーティスト→オーディエンスの一方向での発信だったが、それを双方向にする
・オーディエンス→アーティストの貢献は作品やグッズを買う事でしかできなかったが、お金のないオーディエンスもアプリを介して貢献したい！

**Comment by s-kamada** [comment]
# "Power of us"
に決まりました

**Comment by Sntree2mi8** [comment]
決まったのでクローズ
